-- Deprecated mirror file.
--
-- The canonical QuickFlex database schema is the repository-root
-- `supabase-schema.sql` file. Keep this file as a pointer only so future
-- agents do not accidentally maintain two diverging schema sources.
