create table if not exists public.quickflex_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text not null default '사용자',
  driver_type text not null default 'backup' check (driver_type in ('backup', 'fixed')),
  status text not null default 'pending' check (status in ('pending', 'approved', 'blocked')),
  role text not null default 'driver' check (role in ('driver', 'admin')),
  fixed_routes text[] not null default '{}',
  goal_amount integer not null default 6000000,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quickflex_route_rates (
  id bigint generated by default as identity primary key,
  user_id text not null,
  route text not null,
  current_unit integer not null,
  updated_at timestamptz not null default now(),
  unique (user_id, route)
);

create table if not exists public.quickflex_day_records (
  id bigint generated by default as identity primary key,
  user_id text not null,
  work_date date not null,
  is_off boolean not null default false,
  fresh_count integer not null default 0,
  fresh_unit integer not null default 100,
  backup_unit integer not null default 30,
  driver_type text not null default 'backup' check (driver_type in ('backup', 'fixed')),
  updated_at timestamptz not null default now(),
  unique (user_id, work_date)
);

create table if not exists public.quickflex_day_route_items (
  id bigint generated by default as identity primary key,
  user_id text not null,
  work_date date not null,
  route text not null,
  delivery_count integer not null default 0,
  unit_snapshot integer not null default 0,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.quickflex_route_bundles (
  id bigint generated by default as identity primary key,
  label text not null,
  routes text[] not null default '{}',
  active boolean not null default true,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now(),
  unique (label)
);

create table if not exists public.quickflex_daily_inspections (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  inspection_date date not null,
  status text not null default 'completed' check (status in ('completed', 'no_operation')),
  results jsonb not null default '{}'::jsonb check (
    jsonb_typeof(results) = 'object'
    and jsonb_array_length(jsonb_path_query_array(results, '$.*')) = 11
    and results ?& array['item_1', 'item_2', 'item_3', 'item_4', 'item_5', 'item_6', 'item_7', 'item_8', 'item_9', 'item_10', 'item_11']
    and (
      (status = 'completed' and not jsonb_path_exists(results, '$.* ? (@ != "good" && @ != "bad")'))
      or (status = 'no_operation' and not jsonb_path_exists(results, '$.* ? (@ != "no_operation")'))
    )
  ),
  defect_notes text not null default '',
  action_notes text not null default '',
  signed_name text not null,
  signed_at timestamptz not null default now(),
  source text not null default 'app' check (source in ('app', 'legacy_paper')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, inspection_date)
);

alter table public.quickflex_profiles
  add column if not exists email text,
  add column if not exists display_name text not null default '사용자',
  add column if not exists driver_type text not null default 'backup',
  add column if not exists status text not null default 'pending',
  add column if not exists role text not null default 'driver',
  add column if not exists fixed_routes text[] not null default '{}',
  add column if not exists goal_amount integer not null default 6000000,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists freshbag_mode text not null default 'single',
  add column if not exists business_name text not null default '',
  add column if not exists vehicle_number text not null default '',
  add column if not exists app_notice_version text not null default '';

alter table public.quickflex_day_records
  add column if not exists backup_unit integer not null default 30,
  add column if not exists driver_type text not null default 'backup',
  add column if not exists fresh_solo_count integer not null default 0,
  add column if not exists fresh_linked_count integer not null default 0;

create index if not exists idx_quickflex_profiles_status
  on public.quickflex_profiles (status, role);
create index if not exists idx_quickflex_route_rates_user
  on public.quickflex_route_rates (user_id, route);
create index if not exists idx_quickflex_day_records_user
  on public.quickflex_day_records (user_id, work_date);
create index if not exists idx_quickflex_day_items_user
  on public.quickflex_day_route_items (user_id, work_date, sort_order);
create index if not exists idx_quickflex_route_bundles_active
  on public.quickflex_route_bundles (active, sort_order, label);
create index if not exists idx_quickflex_daily_inspections_user_date
  on public.quickflex_daily_inspections (user_id, inspection_date desc);

alter table public.quickflex_profiles enable row level security;
alter table public.quickflex_route_rates enable row level security;
alter table public.quickflex_day_records enable row level security;
alter table public.quickflex_day_route_items enable row level security;
alter table public.quickflex_route_bundles enable row level security;
alter table public.quickflex_daily_inspections enable row level security;

revoke all on table public.quickflex_daily_inspections from anon;
revoke all on table public.quickflex_daily_inspections from authenticated;
grant select, insert, update, delete on table public.quickflex_daily_inspections to authenticated;
revoke all on sequence public.quickflex_daily_inspections_id_seq from anon;
revoke all on sequence public.quickflex_daily_inspections_id_seq from authenticated;
grant usage, select on sequence public.quickflex_daily_inspections_id_seq to authenticated;

create or replace function public.quickflex_is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.quickflex_profiles
    where id = auth.uid()
      and role = 'admin'
      and status = 'approved'
  );
$$;

create or replace function public.quickflex_is_approved()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.quickflex_profiles
    where id = auth.uid()
      and status = 'approved'
  );
$$;

create or replace function public.quickflex_is_admin_rate_owner(owner_id text)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.quickflex_profiles
    where id::text = owner_id
      and role = 'admin'
      and status = 'approved'
  );
$$;

create or replace function public.quickflex_guard_profile_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.quickflex_is_admin() then
    return new;
  end if;

  if auth.uid() = old.id then
    new.id := old.id;
    new.email := old.email;
    new.status := old.status;
    new.role := old.role;
    return new;
  end if;

  raise exception 'profile update is not allowed';
end;
$$;

drop trigger if exists quickflex_guard_profile_update_trigger on public.quickflex_profiles;
create trigger quickflex_guard_profile_update_trigger
before update on public.quickflex_profiles
for each row
execute function public.quickflex_guard_profile_update();

create or replace function public.quickflex_bootstrap_first_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (select 1 from public.quickflex_profiles) then
    new.status := 'approved';
    new.role := 'admin';
    if new.display_name is null or new.display_name = '' then
      new.display_name := '관리자';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists quickflex_bootstrap_first_profile_trigger on public.quickflex_profiles;
create trigger quickflex_bootstrap_first_profile_trigger
before insert on public.quickflex_profiles
for each row
execute function public.quickflex_bootstrap_first_profile();

create or replace function public.quickflex_handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $function$
begin
  insert into public.quickflex_profiles (id, email, display_name, driver_type, status, role, fixed_routes)
  values (
    new.id,
    new.email,
    coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), nullif(split_part(coalesce(new.email, ''), '@', 1), ''), '사용자'),
    case when new.raw_user_meta_data ->> 'driver_type' = 'fixed' then 'fixed' else 'backup' end,
    'pending',
    'driver',
    '{}'
  )
  on conflict (id) do nothing;

  return new;
end;
$function$;

drop trigger if exists quickflex_handle_new_auth_user_trigger on auth.users;
create trigger quickflex_handle_new_auth_user_trigger
after insert on auth.users
for each row
execute function public.quickflex_handle_new_auth_user();

create or replace function public.quickflex_ensure_profile(
  profile_email text,
  profile_display_name text,
  profile_driver_type text
)
returns public.quickflex_profiles
language plpgsql
security definer
set search_path = public
as $function$
declare
  result public.quickflex_profiles;
begin
  if auth.uid() is null then
    raise exception 'login is required';
  end if;

  insert into public.quickflex_profiles (id, email, display_name, driver_type, status, role, fixed_routes)
  values (
    auth.uid(),
    profile_email,
    coalesce(nullif(profile_display_name, ''), nullif(split_part(coalesce(profile_email, ''), '@', 1), ''), '사용자'),
    case when profile_driver_type = 'fixed' then 'fixed' else 'backup' end,
    'pending',
    'driver',
    '{}'
  )
  on conflict (id) do update
    set email = coalesce(public.quickflex_profiles.email, excluded.email),
        display_name = case
          when public.quickflex_profiles.display_name is null
            or public.quickflex_profiles.display_name in ('', 'user', '사용자')
          then excluded.display_name
          else public.quickflex_profiles.display_name
        end,
        updated_at = now();

  select *
  into result
  from public.quickflex_profiles
  where id = auth.uid();

  if result.id is null then
    raise exception 'profile could not be created';
  end if;

  return result;
end;
$function$;

grant execute on function public.quickflex_ensure_profile(text, text, text) to authenticated;

revoke execute on function public.quickflex_is_admin() from public, anon;
revoke execute on function public.quickflex_is_approved() from public, anon;
revoke execute on function public.quickflex_is_admin_rate_owner(text) from public, anon;
revoke execute on function public.quickflex_ensure_profile(text, text, text) from public, anon;
grant execute on function public.quickflex_is_admin() to authenticated;
grant execute on function public.quickflex_is_approved() to authenticated;
grant execute on function public.quickflex_is_admin_rate_owner(text) to authenticated;
grant execute on function public.quickflex_ensure_profile(text, text, text) to authenticated;

revoke execute on function public.quickflex_guard_profile_update() from public, anon, authenticated;
revoke execute on function public.quickflex_bootstrap_first_profile() from public, anon, authenticated;
revoke execute on function public.quickflex_handle_new_auth_user() from public, anon, authenticated;

drop policy if exists "quickflex profiles select own or admin" on public.quickflex_profiles;
drop policy if exists "quickflex profiles insert own" on public.quickflex_profiles;
drop policy if exists "quickflex profiles update own" on public.quickflex_profiles;
drop policy if exists "quickflex profiles admin update" on public.quickflex_profiles;
drop policy if exists "quickflex profiles admin delete" on public.quickflex_profiles;

create policy "quickflex profiles select own or admin"
on public.quickflex_profiles
for select
to authenticated
using (id = auth.uid() or public.quickflex_is_admin());

create policy "quickflex profiles insert own"
on public.quickflex_profiles
for insert
to authenticated
with check (id = auth.uid());

create policy "quickflex profiles update own"
on public.quickflex_profiles
for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

create policy "quickflex profiles admin update"
on public.quickflex_profiles
for update
to authenticated
using (public.quickflex_is_admin())
with check (public.quickflex_is_admin());

create policy "quickflex profiles admin delete"
on public.quickflex_profiles
for delete
to authenticated
using (public.quickflex_is_admin() and id <> auth.uid());

drop policy if exists "quickflex route rates select" on public.quickflex_route_rates;
drop policy if exists "quickflex route rates insert" on public.quickflex_route_rates;
drop policy if exists "quickflex route rates update" on public.quickflex_route_rates;
drop policy if exists "quickflex route rates delete" on public.quickflex_route_rates;

create policy "quickflex route rates select"
on public.quickflex_route_rates
for select
to authenticated
using (
  public.quickflex_is_admin()
  or (
    public.quickflex_is_approved()
    and user_id = auth.uid()::text
  )
);

create policy "quickflex route rates insert"
on public.quickflex_route_rates
for insert
to authenticated
with check (
  public.quickflex_is_admin()
  or (user_id = auth.uid()::text and public.quickflex_is_approved())
);

create policy "quickflex route rates update"
on public.quickflex_route_rates
for update
to authenticated
using (
  public.quickflex_is_admin()
  or (user_id = auth.uid()::text and public.quickflex_is_approved())
)
with check (
  public.quickflex_is_admin()
  or (user_id = auth.uid()::text and public.quickflex_is_approved())
);

create policy "quickflex route rates delete"
on public.quickflex_route_rates
for delete
to authenticated
using (
  public.quickflex_is_admin()
  or (user_id = auth.uid()::text and public.quickflex_is_approved())
);

drop policy if exists "quickflex day records select" on public.quickflex_day_records;
drop policy if exists "quickflex day records insert" on public.quickflex_day_records;
drop policy if exists "quickflex day records update" on public.quickflex_day_records;
drop policy if exists "quickflex day records delete" on public.quickflex_day_records;

create policy "quickflex day records select"
on public.quickflex_day_records
for select
to authenticated
using (public.quickflex_is_admin() or (user_id = auth.uid()::text and public.quickflex_is_approved()));

create policy "quickflex day records insert"
on public.quickflex_day_records
for insert
to authenticated
with check (user_id = auth.uid()::text and public.quickflex_is_approved());

create policy "quickflex day records update"
on public.quickflex_day_records
for update
to authenticated
using (user_id = auth.uid()::text and public.quickflex_is_approved())
with check (user_id = auth.uid()::text and public.quickflex_is_approved());

create policy "quickflex day records delete"
on public.quickflex_day_records
for delete
to authenticated
using (public.quickflex_is_admin() or (user_id = auth.uid()::text and public.quickflex_is_approved()));

drop policy if exists "quickflex day items select" on public.quickflex_day_route_items;
drop policy if exists "quickflex day items insert" on public.quickflex_day_route_items;
drop policy if exists "quickflex day items update" on public.quickflex_day_route_items;
drop policy if exists "quickflex day items delete" on public.quickflex_day_route_items;

create policy "quickflex day items select"
on public.quickflex_day_route_items
for select
to authenticated
using (public.quickflex_is_admin() or (user_id = auth.uid()::text and public.quickflex_is_approved()));

create policy "quickflex day items insert"
on public.quickflex_day_route_items
for insert
to authenticated
with check (user_id = auth.uid()::text and public.quickflex_is_approved());

create policy "quickflex day items update"
on public.quickflex_day_route_items
for update
to authenticated
using (user_id = auth.uid()::text and public.quickflex_is_approved())
with check (user_id = auth.uid()::text and public.quickflex_is_approved());

create policy "quickflex day items delete"
on public.quickflex_day_route_items
for delete
to authenticated
using (public.quickflex_is_admin() or (user_id = auth.uid()::text and public.quickflex_is_approved()));

drop policy if exists "quickflex route bundles select" on public.quickflex_route_bundles;
drop policy if exists "quickflex route bundles insert" on public.quickflex_route_bundles;
drop policy if exists "quickflex route bundles update" on public.quickflex_route_bundles;
drop policy if exists "quickflex route bundles delete" on public.quickflex_route_bundles;

create policy "quickflex route bundles select"
on public.quickflex_route_bundles
for select
to authenticated
using (
  exists (
    select 1
    from public.quickflex_profiles
    where id = auth.uid()
      and status = 'approved'
      and (role = 'admin' or active)
  )
);

create policy "quickflex route bundles insert"
on public.quickflex_route_bundles
for insert
to authenticated
with check (
  exists (
    select 1
    from public.quickflex_profiles
    where id = auth.uid()
      and role = 'admin'
      and status = 'approved'
  )
);

create policy "quickflex route bundles update"
on public.quickflex_route_bundles
for update
to authenticated
using (
  exists (
    select 1
    from public.quickflex_profiles
    where id = auth.uid()
      and role = 'admin'
      and status = 'approved'
  )
)
with check (
  exists (
    select 1
    from public.quickflex_profiles
    where id = auth.uid()
      and role = 'admin'
      and status = 'approved'
  )
);

create policy "quickflex route bundles delete"
on public.quickflex_route_bundles
for delete
to authenticated
using (
  exists (
    select 1
    from public.quickflex_profiles
    where id = auth.uid()
      and role = 'admin'
      and status = 'approved'
  )
);

drop policy if exists "quickflex inspections select own or admin" on public.quickflex_daily_inspections;
drop policy if exists "quickflex inspections insert own" on public.quickflex_daily_inspections;
drop policy if exists "quickflex inspections update own" on public.quickflex_daily_inspections;
drop policy if exists "quickflex inspections delete own" on public.quickflex_daily_inspections;

create policy "quickflex inspections select own or admin"
on public.quickflex_daily_inspections
for select
to authenticated
using (
  (select public.quickflex_is_admin())
  or (user_id = (select auth.uid()) and (select public.quickflex_is_approved()))
);

create policy "quickflex inspections insert own"
on public.quickflex_daily_inspections
for insert
to authenticated
with check (user_id = (select auth.uid()) and (select public.quickflex_is_approved()));

create policy "quickflex inspections update own"
on public.quickflex_daily_inspections
for update
to authenticated
using (user_id = (select auth.uid()) and (select public.quickflex_is_approved()))
with check (user_id = (select auth.uid()) and (select public.quickflex_is_approved()));

create policy "quickflex inspections delete own"
on public.quickflex_daily_inspections
for delete
to authenticated
using (user_id = (select auth.uid()) and (select public.quickflex_is_approved()));

comment on table public.quickflex_profiles is 'QuickFlex users and driver type settings';
comment on table public.quickflex_route_rates is 'Current route unit master data per user';
comment on table public.quickflex_day_records is 'Per-day header record values with driver type snapshot';
comment on table public.quickflex_day_route_items is 'Per-day route entries with unit snapshots';
comment on table public.quickflex_route_bundles is 'Admin-managed OCR route bundle correction patterns';
comment on table public.quickflex_daily_inspections is 'QuickFlex account-scoped statutory daily vehicle inspection records';
