create table if not exists public.quickflex_route_rates (
  id bigint generated by default as identity primary key,
  user_id text not null,
  route text not null,
  current_unit integer not null,
  updated_at timestamptz not null default now(),
  unique (user_id, route)
);

create table if not exists public.quickflex_day_records (
  id bigint generated by default as identity primary key,
  user_id text not null,
  work_date date not null,
  is_off boolean not null default false,
  fresh_count integer not null default 0,
  fresh_unit integer not null default 100,
  backup_unit integer not null default 30,
  updated_at timestamptz not null default now(),
  unique (user_id, work_date)
);

create table if not exists public.quickflex_day_route_items (
  id bigint generated by default as identity primary key,
  user_id text not null,
  work_date date not null,
  route text not null,
  delivery_count integer not null default 0,
  unit_snapshot integer not null default 0,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create index if not exists idx_quickflex_route_rates_user
  on public.quickflex_route_rates (user_id, route);
create index if not exists idx_quickflex_day_records_user
  on public.quickflex_day_records (user_id, work_date);
create index if not exists idx_quickflex_day_items_user
  on public.quickflex_day_route_items (user_id, work_date, sort_order);

alter table public.quickflex_route_rates enable row level security;
alter table public.quickflex_day_records enable row level security;
alter table public.quickflex_day_route_items enable row level security;

alter table public.quickflex_day_records
  add column if not exists backup_unit integer not null default 30;

drop policy if exists "quickflex route rates select" on public.quickflex_route_rates;
drop policy if exists "quickflex route rates insert" on public.quickflex_route_rates;
drop policy if exists "quickflex route rates update" on public.quickflex_route_rates;
drop policy if exists "quickflex route rates delete" on public.quickflex_route_rates;

create policy "quickflex route rates select"
on public.quickflex_route_rates
for select
to anon
using (user_id = 'kim-gwanhyun');

create policy "quickflex route rates insert"
on public.quickflex_route_rates
for insert
to anon
with check (user_id = 'kim-gwanhyun');

create policy "quickflex route rates update"
on public.quickflex_route_rates
for update
to anon
using (user_id = 'kim-gwanhyun')
with check (user_id = 'kim-gwanhyun');

create policy "quickflex route rates delete"
on public.quickflex_route_rates
for delete
to anon
using (user_id = 'kim-gwanhyun');

drop policy if exists "quickflex day records select" on public.quickflex_day_records;
drop policy if exists "quickflex day records insert" on public.quickflex_day_records;
drop policy if exists "quickflex day records update" on public.quickflex_day_records;
drop policy if exists "quickflex day records delete" on public.quickflex_day_records;

create policy "quickflex day records select"
on public.quickflex_day_records
for select
to anon
using (user_id = 'kim-gwanhyun');

create policy "quickflex day records insert"
on public.quickflex_day_records
for insert
to anon
with check (user_id = 'kim-gwanhyun');

create policy "quickflex day records update"
on public.quickflex_day_records
for update
to anon
using (user_id = 'kim-gwanhyun')
with check (user_id = 'kim-gwanhyun');

create policy "quickflex day records delete"
on public.quickflex_day_records
for delete
to anon
using (user_id = 'kim-gwanhyun');

drop policy if exists "quickflex day items select" on public.quickflex_day_route_items;
drop policy if exists "quickflex day items insert" on public.quickflex_day_route_items;
drop policy if exists "quickflex day items update" on public.quickflex_day_route_items;
drop policy if exists "quickflex day items delete" on public.quickflex_day_route_items;

create policy "quickflex day items select"
on public.quickflex_day_route_items
for select
to anon
using (user_id = 'kim-gwanhyun');

create policy "quickflex day items insert"
on public.quickflex_day_route_items
for insert
to anon
with check (user_id = 'kim-gwanhyun');

create policy "quickflex day items update"
on public.quickflex_day_route_items
for update
to anon
using (user_id = 'kim-gwanhyun')
with check (user_id = 'kim-gwanhyun');

create policy "quickflex day items delete"
on public.quickflex_day_route_items
for delete
to anon
using (user_id = 'kim-gwanhyun');

comment on table public.quickflex_route_rates is 'Current route unit master data';
comment on table public.quickflex_day_records is 'Per-day header record values';
comment on table public.quickflex_day_route_items is 'Per-day route entries with unit snapshots';
