import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const migration = readFileSync(
  new URL(
    "../supabase/migrations/20260827094035_quickflex_usage_telemetry.sql",
    import.meta.url,
  ),
  "utf8",
);
const schema = readFileSync(new URL("../supabase-schema.sql", import.meta.url), "utf8");
const usageSource = readFileSync(new URL("../src/services/usage.js", import.meta.url), "utf8");
const usage = await import(`data:text/javascript;base64,${Buffer.from(usageSource).toString("base64")}`);

const SESSION_ID = "018f1000-1111-7111-8111-111111111111";
const EVENT_ID = "018f1000-2222-7222-8222-222222222222";
const USER_ID = "018f1000-3333-7333-8333-333333333333";
const OTHER_USER_ID = "018f1000-4444-7444-8444-444444444444";
const OTHER_SESSION_ID = "018f1000-5555-7555-8555-555555555555";

test("usage table accepts only the three event names and exact enumerated properties", () => {
  assert.match(
    migration,
    /event_name in \('app_session_started', 'screen_viewed', 'stats_control_used'\)/,
  );
  assert.match(migration, /event_name = 'app_session_started'[\s\S]*?properties = '\{\}'::jsonb/);
  assert.match(migration, /event_name = 'screen_viewed'[\s\S]*?jsonb_build_object\('screen'/);
  assert.match(migration, /event_name = 'stats_control_used'[\s\S]*?jsonb_build_object\('control'/);
  assert.match(migration, /jsonb_typeof\(properties -> 'screen'\) = 'string'/);
  assert.match(migration, /jsonb_typeof\(properties -> 'control'\) = 'string'/);
  assert.doesNotMatch(migration, /p_(amount|count|route|date|text|device|ip)\b/i);
});

test("raw usage rows cannot be read, changed, or deleted by client roles", () => {
  assert.match(migration, /alter table public\.quickflex_usage_events enable row level security/);
  assert.match(
    migration,
    /revoke all on table public\.quickflex_usage_events from public, anon, authenticated/,
  );
  assert.match(
    migration,
    /grant insert \(user_id, client_event_id, session_id, event_name, properties\)[\s\S]*?to authenticated/,
  );
  assert.doesNotMatch(migration, /grant\s+(select|update|delete)[\s\S]*?quickflex_usage_events/i);
  assert.match(
    migration,
    /create policy "quickflex usage events insert own approved"[\s\S]*?user_id = \(select auth\.uid\(\)\)[\s\S]*?quickflex_is_approved\(\)/,
  );
});

test("tracking RPC is authenticated, approved, RLS-bound, and idempotent", () => {
  assert.match(migration, /primary key \(user_id, client_event_id\)/);
  assert.doesNotMatch(migration, /generated by default as identity/i);
  assert.match(
    migration,
    /create or replace function public\.quickflex_track_usage_event[\s\S]*?security invoker[\s\S]*?set search_path = ''/,
  );
  assert.match(migration, /current_user_id uuid := \(select auth\.uid\(\)\)/);
  assert.match(migration, /p_expected_user_id is null or p_expected_user_id <> current_user_id/);
  assert.match(migration, /approved account required/);
  assert.match(migration, /on conflict \(user_id, client_event_id\) do nothing/);
  assert.match(
    migration,
    /revoke execute on function public\.quickflex_track_usage_event\(uuid, uuid, uuid, text, jsonb\)[\s\S]*?from public, anon, authenticated/,
  );
  assert.match(
    migration,
    /grant execute on function public\.quickflex_track_usage_event\(uuid, uuid, uuid, text, jsonb\)[\s\S]*?to authenticated/,
  );
});

test("only the private summary implementation elevates privileges and it checks admin", () => {
  assert.match(
    migration,
    /create or replace function private\.quickflex_usage_summary_internal[\s\S]*?security definer[\s\S]*?set search_path = ''[\s\S]*?quickflex_is_admin\(\)/,
  );
  assert.match(
    migration,
    /create or replace function public\.quickflex_usage_summary[\s\S]*?security invoker[\s\S]*?private\.quickflex_usage_summary_internal/,
  );
  for (const field of [
    "active_user_count",
    "stats_viewer_count",
    "engaged_user_count",
    "repeat_viewer_count",
    "stats_reach_rate",
    "stats_engagement_rate",
    "repeat_viewer_rate",
  ]) {
    assert.match(migration, new RegExp(`\\b${field}\\b`));
  }
  assert.match(migration, /event\.created_at/);
  assert.match(
    migration,
    /having count\(distinct pg_catalog\.date_trunc\([\s\S]*?'week'[\s\S]*?event\.created_at at time zone 'Asia\/Seoul'[\s\S]*?\)\) >= 2/,
  );
});

test("retention uses a stable named cron.schedule job and never modifies cron.job directly", () => {
  assert.match(migration, /create extension if not exists pg_cron with schema pg_catalog/);
  assert.match(
    migration,
    /cron\.schedule\(\s*'quickflex-usage-events-retention'[\s\S]*?interval '90 days'/,
  );
  assert.doesNotMatch(migration, /(insert into|update|delete from)\s+cron\.job\b/i);
});

test("canonical schema carries the same privacy, primary-key, weekly-repeat, and retention contract", () => {
  for (const source of [migration, schema]) {
    assert.match(source, /create table if not exists public\.quickflex_usage_events/);
    assert.match(source, /primary key \(user_id, client_event_id\)/);
    assert.match(source, /security invoker[\s\S]*?quickflex_track_usage_event|quickflex_track_usage_event[\s\S]*?security invoker/);
    assert.match(source, /event\.created_at at time zone 'Asia\/Seoul'/);
    assert.match(source, /'quickflex-usage-events-retention'/);
  }
});

test("client sanitizer rejects extra, sensitive, and free-text properties", () => {
  assert.deepEqual(usage.sanitizeUsageProperties("app_session_started", {}), {});
  assert.deepEqual(usage.sanitizeUsageProperties("screen_viewed", { screen: "stats" }), {
    screen: "stats",
  });
  assert.deepEqual(
    usage.sanitizeUsageProperties("stats_control_used", { control: "range_changed" }),
    { control: "range_changed" },
  );
  assert.equal(usage.sanitizeUsageProperties("screen_viewed", { screen: "stats", amount: 100 }), null);
  assert.equal(usage.sanitizeUsageProperties("stats_control_used", { control: "typed note" }), null);
  assert.equal(usage.sanitizeUsageProperties("unknown", {}), null);
});

test("client tracking sends the minimum RPC payload and fails open", async () => {
  const calls = [];
  const db = {
    async rpc(name, params) {
      calls.push({ name, params });
      return { data: [{ accepted: true, inserted: true }], error: null };
    },
  };
  assert.equal(await usage.trackUsageEvent(
    db,
    "screen_viewed",
    { screen: "stats" },
    { sessionId: SESSION_ID, clientEventId: EVENT_ID, expectedUserId: USER_ID },
  ), true);
  assert.deepEqual(calls, [{
    name: "quickflex_track_usage_event",
    params: {
      p_client_event_id: EVENT_ID,
      p_session_id: SESSION_ID,
      p_expected_user_id: USER_ID,
      p_event_name: "screen_viewed",
      p_properties: { screen: "stats" },
    },
  }]);

  assert.equal(await usage.trackUsageEvent(null, "screen_viewed", { screen: "stats" }), false);
  assert.equal(await usage.trackUsageEvent(db, "screen_viewed", { screen: "stats" }, {
    sessionId: SESSION_ID,
    clientEventId: EVENT_ID,
  }), false, "an expected account is mandatory");
  assert.equal(await usage.trackUsageEvent(db, "screen_viewed", { screen: "stats", route: "324C" }), false);
  assert.equal(await usage.trackUsageEvent({ rpc: async () => { throw new Error("offline"); } },
    "app_session_started", {}, {
      sessionId: SESSION_ID,
      clientEventId: EVENT_ID,
      expectedUserId: USER_ID,
    }), false);
});

test("session UUID persists only in session storage and summary validates its window", async () => {
  const values = new Map();
  const storage = {
    getItem: (key) => values.get(key) || null,
    setItem: (key, value) => values.set(key, value),
  };
  const sessionId = usage.getUsageSessionId({ storage, uuidFactory: () => SESSION_ID, userId: USER_ID });
  assert.equal(sessionId, SESSION_ID);
  assert.equal(values.get(usage.usageSessionStorageKey(USER_ID)), SESSION_ID);
  const otherSessionId = usage.getUsageSessionId({
    storage,
    uuidFactory: () => OTHER_SESSION_ID,
    userId: OTHER_USER_ID,
  });
  assert.equal(otherSessionId, OTHER_SESSION_ID);
  assert.equal(values.get(usage.usageSessionStorageKey(OTHER_USER_ID)), OTHER_SESSION_ID);
  assert.notEqual(usage.usageSessionStorageKey(USER_ID), usage.usageSessionStorageKey(OTHER_USER_ID));

  const db = { rpc: async (name, params) => ({ data: [{ name, days: params.p_window_days }], error: null }) };
  assert.deepEqual(await usage.fetchUsageSummary(db, { windowDays: 14 }), {
    name: "quickflex_usage_summary",
    days: 14,
  });
  await assert.rejects(() => usage.fetchUsageSummary(db, { windowDays: 0 }), RangeError);
  await assert.rejects(() => usage.fetchUsageSummary(null), /unavailable/);
});
