export function buildSchedulePrompt(ownerName: string, year: number, month: number) {
  return [
    `${ownerName}의 쿠팡 퀵플렉스 스케줄표 이미지를 읽고 결과를 JSON으로 반환하세요.`,
    `정산 기준 월은 ${year}년 ${month}월입니다. 표 헤더의 날짜를 정확히 매핑해 주세요.`,
    "",
    "추출 규칙:",
    `1) ${ownerName} 본인 행만 읽습니다. 다른 기사 행은 무시합니다.`,
    "2) 셀에 구역 코드(숫자 3자리 + 영문 대문자 1자리, 예: 302C, 313B)가 있으면 routes 배열에 그 코드만 담습니다.",
    "3) 한 셀에 여러 구역이 있으면 모두 배열에 포함합니다 (예: ['302C', '304B']).",
    "4) 셀이 비었거나 휴무/OFF/-/X 같은 표시면 routes는 null 입니다.",
    "5) 영문은 항상 대문자로 정규화. 공백·특수문자 제거.",
    "6) 표에 없는 날짜는 결과에 포함하지 마세요.",
    "",
    "출력 형식 (JSON만, 다른 설명 금지):",
    "{",
    '  "days": [',
    '    { "date": "YYYY-MM-DD", "routes": ["302C"] },',
    '    { "date": "YYYY-MM-DD", "routes": ["302C", "304B"] },',
    '    { "date": "YYYY-MM-DD", "routes": null }',
    "  ]",
    "}",
    "",
    "예시:",
    `- ${ownerName} 행 5월 3일 셀에 "302C" → { "date": "${year}-${String(month).padStart(2, "0")}-03", "routes": ["302C"] }`,
    `- 같은 행 5월 4일 셀이 비어 있음 → { "date": "${year}-${String(month).padStart(2, "0")}-04", "routes": null }`,
    `- 5월 5일 셀에 "302C 304B" 두 개 → { "date": "${year}-${String(month).padStart(2, "0")}-05", "routes": ["302C", "304B"] }`,
  ].join("\n");
}

export function buildSettlementPrompt(ownerName: string) {
  return [
    `${ownerName}의 쿠팡 QuickFlex 정산표 이미지를 읽고 JSON만 반환하세요.`,
    "",
    "메인 배송 행만 읽습니다. 우측 요약 박스, 하단 차감/상세 행은 무시하세요.",
    "유효한 행은 보통 구분, ID, Route, 배송일자, 캠프명, 배송유형, 배송건수(파손), 반품, 합계, 추가 인센티브, 금액 컬럼을 가집니다.",
    "",
    "추출 규칙:",
    "- Route는 숫자 3자리 + 영문 대문자 1자리 (302C, 407D 등)만 유효. 그 외는 제외.",
    "- deliveryCount는 '배송건수(파손)' 컬럼 값. 없으면 '합계'.",
    "- amount는 '금액' 컬럼 값. '총금액', '지급금액', '공급가액', '세액', '차감내역', '프레시백', '에코백', '백업 인센티브' 박스 값은 절대 사용 금지.",
    "- '미계약 라우트' 또는 Route가 비어있는 행 무시.",
    "- 숫자에서 콤마 제거.",
    "- 단가는 계산하지 마세요. 클라이언트가 amount / deliveryCount로 계산합니다.",
    "- date는 YYYY-MM-DD 형식. 추출이 모호하면 빈 문자열로.",
    "",
    "출력 형식 (JSON만):",
    "{",
    '  "rows": [',
    '    { "route": "302C", "date": "2025-10-29", "deliveryCount": 250, "amount": 241250, "extraIncentive": 15 }',
    "  ]",
    "}",
  ].join("\n");
}
