-- Server-only data for the QuickFlex -> Google Calendar integration. These
-- tables stay in public so Supabase Edge Functions can reach them through the
-- supported Data API, but RLS has no browser policies and browser roles have no
-- privileges. Only service_role receives table access below.

create table if not exists public.quickflex_calendar_connections (
  user_id uuid primary key references auth.users(id) on delete cascade,
  token_ciphertext text not null check (char_length(token_ciphertext) between 32 and 20000),
  calendar_id text not null default '',
  connection_status text not null default 'connected'
    check (connection_status in ('connected', 'disconnected', 'needs_reconnect')),
  expires_at timestamptz,
  last_successful_at timestamptz,
  last_error text not null default '',
  sync_lease_until timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quickflex_calendar_oauth_states (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  state_hash text not null unique check (char_length(state_hash) between 32 and 128),
  return_to text not null check (char_length(return_to) between 1 and 2000),
  expires_at timestamptz not null,
  consumed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists quickflex_calendar_oauth_states_expiry_idx
  on public.quickflex_calendar_oauth_states (expires_at)
  where consumed_at is null;

create table if not exists public.quickflex_calendar_event_mappings (
  user_id uuid not null references auth.users(id) on delete cascade,
  work_date date not null,
  google_event_id text not null check (char_length(google_event_id) between 5 and 1024),
  google_etag text not null default '',
  last_payload_hash text not null check (char_length(last_payload_hash) between 32 and 128),
  last_payload jsonb not null check (jsonb_typeof(last_payload) = 'object'),
  sync_state text not null default 'synced' check (sync_state in ('synced', 'conflict')),
  conflict_reason text not null default '',
  updated_at timestamptz not null default now(),
  primary key (user_id, work_date)
);

create table if not exists public.quickflex_calendar_sync_jobs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  active_key text unique check (active_key is null or char_length(active_key) between 32 and 128),
  status text not null default 'queued'
    check (status in ('queued', 'running', 'succeeded', 'failed', 'conflict')),
  attempt_count integer not null default 0 check (attempt_count between 0 and 20),
  payload jsonb not null check (jsonb_typeof(payload) = 'object'),
  run_after timestamptz not null default now(),
  locked_at timestamptz,
  finished_at timestamptz,
  error_message text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists quickflex_calendar_sync_jobs_ready_idx
  on public.quickflex_calendar_sync_jobs (status, run_after, id)
  where status = 'queued';

alter table public.quickflex_calendar_connections enable row level security;
alter table public.quickflex_calendar_oauth_states enable row level security;
alter table public.quickflex_calendar_event_mappings enable row level security;
alter table public.quickflex_calendar_sync_jobs enable row level security;

revoke all on table public.quickflex_calendar_connections from public, anon, authenticated;
revoke all on table public.quickflex_calendar_oauth_states from public, anon, authenticated;
revoke all on table public.quickflex_calendar_event_mappings from public, anon, authenticated;
revoke all on table public.quickflex_calendar_sync_jobs from public, anon, authenticated;

grant select, insert, update, delete on table public.quickflex_calendar_connections to service_role;
grant select, insert, update, delete on table public.quickflex_calendar_oauth_states to service_role;
grant select, insert, update, delete on table public.quickflex_calendar_event_mappings to service_role;
grant select, insert, update, delete on table public.quickflex_calendar_sync_jobs to service_role;
grant usage, select on sequence public.quickflex_calendar_oauth_states_id_seq to service_role;
grant usage, select on sequence public.quickflex_calendar_sync_jobs_id_seq to service_role;
