-- Temporary tester-only Android diagnostics. Drop this table when measurement testing ends.
create table if not exists public.quickflex_measurement_diagnostics (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_event_id text not null,
  captured_at timestamptz not null,
  level text not null,
  summary text not null,
  details jsonb not null default '[]'::jsonb check (jsonb_typeof(details) = 'array'),
  app_version text not null default '',
  created_at timestamptz not null default now(),
  unique (user_id, client_event_id)
);

alter table public.quickflex_measurement_diagnostics enable row level security;

revoke all on table public.quickflex_measurement_diagnostics from public, anon;
grant select, insert, delete on table public.quickflex_measurement_diagnostics to authenticated;
grant usage, select on sequence public.quickflex_measurement_diagnostics_id_seq to authenticated;

drop policy if exists "quickflex measurement diagnostics tester insert" on public.quickflex_measurement_diagnostics;
drop policy if exists "quickflex measurement diagnostics admin select" on public.quickflex_measurement_diagnostics;
drop policy if exists "quickflex measurement diagnostics admin delete" on public.quickflex_measurement_diagnostics;

create policy "quickflex measurement diagnostics tester insert"
on public.quickflex_measurement_diagnostics
for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and lower(coalesce((select auth.jwt() ->> 'email'), '')) = 'jamaica8612@gmail.com'
  and (select public.quickflex_is_approved())
);

create policy "quickflex measurement diagnostics admin select"
on public.quickflex_measurement_diagnostics
for select
to authenticated
using ((select public.quickflex_is_admin()));

create policy "quickflex measurement diagnostics admin delete"
on public.quickflex_measurement_diagnostics
for delete
to authenticated
using ((select public.quickflex_is_admin()));

comment on table public.quickflex_measurement_diagnostics is
  'Temporary tester-only sanitized Android measurement diagnostics';
